version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: "/mjob"
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: "/mjob"
    schedule:
      interval: daily
