# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # XXX would be nice to have
    # - $(go env GOPATH)/bin/go-bindata -pkg migrations -ignore '\.go$' -prefix pkg/backend/pg/migrations/ -o pkg/backend/pg/migrations/data.go pkg/backend/pg/migrations
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: job-manager
    env:
      - CGO_ENABLED=0
    main: ./cmd/job-manager
    binary: job-manager
    ldflags: -s -w -X github.com/jeffrom/job-manager/release.Version={{.Version}} -X github.com/jeffrom/job-manager/release.Commit={{.ShortCommit}} -X github.com/jeffrom/job-manager/release.Date={{.Date}}
  - id: jobctl
    env:
      - CGO_ENABLED=0
    main: ./cmd/jobctl
    binary: jobctl
    ldflags: -s -w -X github.com/jeffrom/job-manager/release.Version={{.Version}} -X github.com/jeffrom/job-manager/release.Commit={{.ShortCommit}} -X github.com/jeffrom/job-manager/release.Date={{.Date}}

dockers:
- dockerfile: .goreleaser/Dockerfile
  ids:
    - job-manager
  image_templates:
  - "jeffmartin1117/job-manager:latest"
  - "jeffmartin1117/job-manager:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  build_flag_templates:
  - "--label=org.label-schema.schema-version=1.0"
  - "--label=org.label-schema.version={{.Version}}"
  - "--label=org.label-schema.name={{.ProjectName}}"
  - "--build-arg=VERSION={{.Version}}"
  - "--build-arg=COMMIT={{.ShortCommit}}"
  - "--build-arg=DATE={{.Date}}"
- dockerfile: .goreleaser/jobctl.Dockerfile
  ids:
    - jobctl
  image_templates:
  - "jeffmartin1117/jobctl:latest"
  - "jeffmartin1117/jobctl:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
  build_flag_templates:
  - "--label=org.label-schema.schema-version=1.0"
  - "--label=org.label-schema.version={{.Version}}"
  - "--label=org.label-schema.name={{.ProjectName}}"
  - "--build-arg=VERSION={{.Version}}"
  - "--build-arg=COMMIT={{.ShortCommit}}"
  - "--build-arg=DATE={{.Date}}"

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
    - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
